build.rs: remove target darknet source files right before copying them
This solves the `OS error 13` permissions problem, by allowing the build script to clobber read-only files when copying libraries across.

In particular, git `pack` files are created with `555` permissions, which means they weren't being properly overwritten by the build script, which resulted in the following build failures:
```
error: failed to run custom build command for `darknet-sys v0.3.1 (https://github.com/tonarino/darknet-sys-rust?branch=openmp-configurable#ed9b0b4a)`

Caused by:
  process didn't exit successfully: `/home/strohel/work/portal/target/debug/build/darknet-sys-13f789a883e167c3/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=DARKNET_SRC
  cargo:rerun-if-env-changed=DARKNET_INCLUDE_PATH
  cargo:rerun-if-env-changed=CUDA_PATH
  cargo:rerun-if-env-changed=CUDA_ARCHITECTURES
  cargo:rerun-if-env-changed=DARKNET_ENABLE_OPENMP
  cargo:rerun-if-env-changed=/home/strohel/work/portal/target/debug/build/darknet-sys-7ad42202ae742168/out/bindings.rs
  process: "/home/strohel/.cargo/git/checkouts/darknet-sys-rust-cf3c15bddd28ea3e/ed9b0b4/darknet"
    copy: "/home/strohel/.cargo/git/checkouts/darknet-sys-rust-cf3c15bddd28ea3e/ed9b0b4/darknet/.gitignore" -> "/home/strohel/work/portal/target/debug/build/darknet-sys-7ad42202ae742168/out/darknet/.gitignore"
  (...)
    copy: "/home/strohel/.cargo/git/checkouts/darknet-sys-rust-cf3c15bddd28ea3e/ed9b0b4/darknet/.git/refs/heads/master" -> "/home/strohel/work/portal/target/debug/build/darknet-sys-7ad42202ae742168/out/darknet/.git/refs/heads/master"
  process: "/home/strohel/.cargo/git/checkouts/darknet-sys-rust-cf3c15bddd28ea3e/ed9b0b4/darknet/.git/objects"
  process: "/home/strohel/.cargo/git/checkouts/darknet-sys-rust-cf3c15bddd28ea3e/ed9b0b4/darknet/.git/objects/pack"
    copy: "/home/strohel/.cargo/git/checkouts/darknet-sys-rust-cf3c15bddd28ea3e/ed9b0b4/darknet/.git/objects/pack/pack-83da3357e7e355ccb5a09569a7336054d38eba2d.idx" -> "/home/strohel/work/portal/target/debug/build/darknet-sys-7ad42202ae742168/out/darknet/.git/objects/pack/pack-83da3357e7e355ccb5a09569a7336054d38eba2d.idx"

  --- stderr
  Error: Permission denied (os error 13)
warning: build failed, waiting for other jobs to finish...
error: build failed
```